export const NEW_GALLERYIMG_REQUEST = "NEW_GALLERYIMG_REQUEST";
export const NEW_GALLERYIMG_SUCCESS = "NEW_GALLERYIMG_SUCCESS";
export const NEW_GALLERYIMG_RESET = "NEW_GALLERYIMG_RESET";
export const NEW_GALLERYIMG_FAIL = "NEW_GALLERYIMG_FAIL";

export const ALL_GALLERYIMGS_REQUEST = "ALL_GALLERYIMGS_REQUEST";
export const ALL_GALLERYIMGS_SUCCESS = "ALL_GALLERYIMGS_SUCCESS";
export const ALL_GALLERYIMGS_FAIL = "ALL_GALLERYIMGS_FAIL";

export const GET_GALLERYIMG_REQUEST = "GET_GALLERYIMG_REQUEST";
export const GET_GALLERYIMG_SUCCESS = "GET_GALLERYIMG_SUCCESS";
export const GET_GALLERYIMG_FAIL = "GET_GALLERYIMG_FAIL";

// export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
// export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
// export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";
// export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const DELETE_GALLERYIMG_REQUEST = "DELETE_GALLERYIMG_REQUEST";
export const DELETE_GALLERYIMG_SUCCESS = "DELETE_GALLERYIMG_SUCCESS";
export const DELETE_GALLERYIMG_RESET = "DELETE_GALLERYIMG_RESET";
export const DELETE_GALLERYIMG_FAIL = "DELETE_GALLERYIMG_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
