export const NEW_BANNER_REQUEST = "NEW_BANNER_REQUEST";
export const NEW_BANNER_SUCCESS = "NEW_BANNER_SUCCESS";
export const NEW_BANNER_RESET = "NEW_BANNER_RESET";
export const NEW_BANNER_FAIL = "NEW_BANNER_FAIL";

export const ALL_BANNERS_REQUEST = "ALL_BANNERS_REQUEST";
export const ALL_BANNERS_SUCCESS = "ALL_BANNERS_SUCCESS";
export const ALL_BANNERS_FAIL = "ALL_BANNERS_FAIL";

export const GET_BANNER_REQUEST = "GET_BANNER_REQUEST";
export const GET_BANNER_SUCCESS = "GET_BANNER_SUCCESS";
export const GET_BANNER_FAIL = "GET_BANNER_FAIL";

// export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
// export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
// export const UPDATE_CATEGORY_RESET = "UPDATE_CATEGORY_RESET";
// export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_RESET = "DELETE_BANNER_RESET";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
